### ISSUE TITLE
S3 Upload fails with XAmzContentSHA256Mismatch error on Linode Object Storage

### ISSUE THREAD

**Issue by dpasman** [siderolabs/talos-backup#36]
### Description
When using talos-backup to store backups on Linode Object Storage (S3-compatible), uploads consistently fail with a SHA256 mismatch error. 

### Steps to reproduce
1. Configure talos-backup with Linode Object Storage credentials
2. Run a backup job
3. Observe the SHA256 mismatch error in logs

### Error message
failed to push encrypted snapshot: failed to upload "test-cluster-2025-03-27T12:54:58Z.snap.age" snapshot to s3: operation error S3: PutObject, https response error StatusCode: 400, RequestID: XXX-default, HostID: XXX-default-default, api error XAmzContentSHA256Mismatch: UnknownError

### Current configuration
```yaml
env:
  - name: CUSTOM_S3_ENDPOINT
    value: "https://eu-central-1.linodeobjects.com"
  - name: BUCKET
    value: "[bucket-name]"
  - name: AWS_REGION
    value: "eu-central-1"
  - name: USE_PATH_STYLE
    value: "true" # tried both false and true
...
```

Troubleshooting attempts
- Tried with DISABLE_ENCRYPTION=true but still getting the same error
- Confirmed AWS credentials are correct and have proper permissions
- Other S3 clients can successfully upload to the same bucket
- Similar applications offer a checksumAlgorithm: "" option to disable or modify checksum verification
